# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instrumentBuilder.ui'
#
# Created: Sat Jul 25 22:50:47 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(943, 682)
        Dialog.setMinimumSize(QtCore.QSize(811, 682))
        Dialog.setMaximumSize(QtCore.QSize(943, 682))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.createInstrumentPushButton = QtGui.QPushButton(self.groupBox)
        self.createInstrumentPushButton.setObjectName(_fromUtf8("createInstrumentPushButton"))
        self.horizontalLayout.addWidget(self.createInstrumentPushButton)
        self.setTabContentsPushButton = QtGui.QPushButton(self.groupBox)
        self.setTabContentsPushButton.setObjectName(_fromUtf8("setTabContentsPushButton"))
        self.horizontalLayout.addWidget(self.setTabContentsPushButton)
        self.pushButton_10 = QtGui.QPushButton(self.groupBox)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.enableInstrumentPushButton = QtGui.QPushButton(self.groupBox)
        self.enableInstrumentPushButton.setObjectName(_fromUtf8("enableInstrumentPushButton"))
        self.horizontalLayout.addWidget(self.enableInstrumentPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.instrumentBuilderTabWidget = QtGui.QTabWidget(Dialog)
        self.instrumentBuilderTabWidget.setObjectName(_fromUtf8("instrumentBuilderTabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setMinimumSize(QtCore.QSize(136, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_3 = QtGui.QLineEdit(self.tab)
        self.lineEdit_3.setMaxLength(15)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_5.addWidget(self.lineEdit_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setMinimumSize(QtCore.QSize(136, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setMaxLength(45)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.textBrowser = QtGui.QTextBrowser(self.tab)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout_2.addWidget(self.textBrowser, 8, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setMinimumSize(QtCore.QSize(136, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.lineEdit_4 = QtGui.QLineEdit(self.tab)
        self.lineEdit_4.setMaxLength(6)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_6.addWidget(self.lineEdit_4)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setMinimumSize(QtCore.QSize(136, 0))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEdit_5 = QtGui.QLineEdit(self.tab)
        self.lineEdit_5.setMaxLength(45)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_8.addWidget(self.lineEdit_5)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setMinimumSize(QtCore.QSize(136, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_4.addWidget(self.comboBox)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setMinimumSize(QtCore.QSize(136, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_2.setMaxLength(50)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setMinimumSize(QtCore.QSize(136, 0))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.comboBox_2 = QtGui.QComboBox(self.tab)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.horizontalLayout_7.addWidget(self.comboBox_2)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 7, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 9, 0, 1, 1)
        self.instrumentBuilderTabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setMinimumSize(QtCore.QSize(90, 0))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.lineEdit_6 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_9.addWidget(self.lineEdit_6)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setMinimumSize(QtCore.QSize(90, 0))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_10.addWidget(self.label_11)
        self.lineEdit_7 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_10.addWidget(self.lineEdit_7)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setMinimumSize(QtCore.QSize(90, 0))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_11.addWidget(self.label_12)
        self.comboBox_3 = QtGui.QComboBox(self.tab_2)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.horizontalLayout_11.addWidget(self.comboBox_3)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 2, 0, 1, 1)
        self.textBrowser_2 = QtGui.QTextBrowser(self.tab_2)
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.gridLayout_3.addWidget(self.textBrowser_2, 5, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setMinimumSize(QtCore.QSize(90, 0))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_12.addWidget(self.label_13)
        self.lineEdit_28 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_28.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.horizontalLayout_12.addWidget(self.lineEdit_28)
        self.label_33 = QtGui.QLabel(self.tab_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_12.addWidget(self.label_33)
        self.lineEdit_29 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_29.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.horizontalLayout_12.addWidget(self.lineEdit_29)
        self.label_34 = QtGui.QLabel(self.tab_2)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_12.addWidget(self.label_34)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem11)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 3, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 4, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem12, 6, 0, 1, 1)
        self.instrumentBuilderTabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_24 = QtGui.QLabel(self.tab_3)
        self.label_24.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_22.addWidget(self.label_24)
        self.label_25 = QtGui.QLabel(self.tab_3)
        self.label_25.setMaximumSize(QtCore.QSize(142, 16777215))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_22.addWidget(self.label_25)
        self.label_26 = QtGui.QLabel(self.tab_3)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_22.addWidget(self.label_26)
        self.gridLayout_4.addLayout(self.horizontalLayout_22, 0, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_15 = QtGui.QLabel(self.tab_3)
        self.label_15.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_13.addWidget(self.label_15)
        self.lineEdit_8 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.horizontalLayout_13.addWidget(self.lineEdit_8)
        self.lineEdit_17 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_17.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.horizontalLayout_13.addWidget(self.lineEdit_17)
        self.pushButton = QtGui.QPushButton(self.tab_3)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_13.addWidget(self.pushButton)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem13)
        self.gridLayout_4.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_16 = QtGui.QLabel(self.tab_3)
        self.label_16.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_14.addWidget(self.label_16)
        self.lineEdit_9 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.horizontalLayout_14.addWidget(self.lineEdit_9)
        self.lineEdit_18 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_18.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.horizontalLayout_14.addWidget(self.lineEdit_18)
        self.pushButton_2 = QtGui.QPushButton(self.tab_3)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_14.addWidget(self.pushButton_2)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem14)
        self.gridLayout_4.addLayout(self.horizontalLayout_14, 2, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_17 = QtGui.QLabel(self.tab_3)
        self.label_17.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_15.addWidget(self.label_17)
        self.lineEdit_10 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.horizontalLayout_15.addWidget(self.lineEdit_10)
        self.lineEdit_19 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_19.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.horizontalLayout_15.addWidget(self.lineEdit_19)
        self.pushButton_3 = QtGui.QPushButton(self.tab_3)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_15.addWidget(self.pushButton_3)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem15)
        self.gridLayout_4.addLayout(self.horizontalLayout_15, 3, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_18 = QtGui.QLabel(self.tab_3)
        self.label_18.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_16.addWidget(self.label_18)
        self.lineEdit_11 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_11.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.horizontalLayout_16.addWidget(self.lineEdit_11)
        self.lineEdit_20 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_20.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.horizontalLayout_16.addWidget(self.lineEdit_20)
        self.pushButton_4 = QtGui.QPushButton(self.tab_3)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_16.addWidget(self.pushButton_4)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem16)
        self.gridLayout_4.addLayout(self.horizontalLayout_16, 4, 0, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_19 = QtGui.QLabel(self.tab_3)
        self.label_19.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_17.addWidget(self.label_19)
        self.lineEdit_12 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_12.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.horizontalLayout_17.addWidget(self.lineEdit_12)
        self.lineEdit_21 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_21.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.horizontalLayout_17.addWidget(self.lineEdit_21)
        self.pushButton_5 = QtGui.QPushButton(self.tab_3)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_17.addWidget(self.pushButton_5)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem17)
        self.gridLayout_4.addLayout(self.horizontalLayout_17, 5, 0, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_20 = QtGui.QLabel(self.tab_3)
        self.label_20.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_18.addWidget(self.label_20)
        self.lineEdit_13 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_13.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.horizontalLayout_18.addWidget(self.lineEdit_13)
        self.lineEdit_22 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_22.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.horizontalLayout_18.addWidget(self.lineEdit_22)
        self.pushButton_6 = QtGui.QPushButton(self.tab_3)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_18.addWidget(self.pushButton_6)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem18)
        self.gridLayout_4.addLayout(self.horizontalLayout_18, 6, 0, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_21 = QtGui.QLabel(self.tab_3)
        self.label_21.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_19.addWidget(self.label_21)
        self.lineEdit_14 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_14.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.horizontalLayout_19.addWidget(self.lineEdit_14)
        self.lineEdit_23 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_23.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.horizontalLayout_19.addWidget(self.lineEdit_23)
        self.pushButton_7 = QtGui.QPushButton(self.tab_3)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_19.addWidget(self.pushButton_7)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem19)
        self.gridLayout_4.addLayout(self.horizontalLayout_19, 7, 0, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_22 = QtGui.QLabel(self.tab_3)
        self.label_22.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_20.addWidget(self.label_22)
        self.lineEdit_15 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_15.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.horizontalLayout_20.addWidget(self.lineEdit_15)
        self.lineEdit_24 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_24.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.horizontalLayout_20.addWidget(self.lineEdit_24)
        self.pushButton_8 = QtGui.QPushButton(self.tab_3)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_20.addWidget(self.pushButton_8)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem20)
        self.gridLayout_4.addLayout(self.horizontalLayout_20, 8, 0, 1, 1)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_21.addWidget(self.label_23)
        self.lineEdit_16 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_16.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.horizontalLayout_21.addWidget(self.lineEdit_16)
        self.lineEdit_25 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_25.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.horizontalLayout_21.addWidget(self.lineEdit_25)
        self.pushButton_9 = QtGui.QPushButton(self.tab_3)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_21.addWidget(self.pushButton_9)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem21)
        self.gridLayout_4.addLayout(self.horizontalLayout_21, 9, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.tab_3)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_4.addWidget(self.label_27, 10, 0, 1, 1)
        self.textBrowser_3 = QtGui.QTextBrowser(self.tab_3)
        self.textBrowser_3.setObjectName(_fromUtf8("textBrowser_3"))
        self.gridLayout_4.addWidget(self.textBrowser_3, 11, 0, 1, 1)
        self.instrumentBuilderTabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.textBrowser_4 = QtGui.QTextBrowser(self.tab_4)
        self.textBrowser_4.setObjectName(_fromUtf8("textBrowser_4"))
        self.gridLayout_5.addWidget(self.textBrowser_4, 3, 0, 1, 1)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_29 = QtGui.QLabel(self.tab_4)
        self.label_29.setMinimumSize(QtCore.QSize(50, 0))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_24.addWidget(self.label_29)
        self.checkBox_2 = QtGui.QCheckBox(self.tab_4)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayout_24.addWidget(self.checkBox_2)
        self.lineEdit_27 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_27.setMaxLength(10)
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.horizontalLayout_24.addWidget(self.lineEdit_27)
        self.label_31 = QtGui.QLabel(self.tab_4)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_24.addWidget(self.label_31)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem22)
        self.gridLayout_5.addLayout(self.horizontalLayout_24, 1, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.tab_4)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_5.addWidget(self.label_32, 2, 0, 1, 1)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_28 = QtGui.QLabel(self.tab_4)
        self.label_28.setMinimumSize(QtCore.QSize(50, 0))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_23.addWidget(self.label_28)
        self.checkBox = QtGui.QCheckBox(self.tab_4)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_23.addWidget(self.checkBox)
        self.lineEdit_26 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_26.setMaxLength(10)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.horizontalLayout_23.addWidget(self.lineEdit_26)
        self.label_30 = QtGui.QLabel(self.tab_4)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_23.addWidget(self.label_30)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem23)
        self.gridLayout_5.addLayout(self.horizontalLayout_23, 0, 0, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem24, 4, 0, 1, 1)
        self.instrumentBuilderTabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_35 = QtGui.QLabel(self.tab_5)
        self.label_35.setMinimumSize(QtCore.QSize(90, 0))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_25.addWidget(self.label_35)
        self.lineEdit_30 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_30.setObjectName(_fromUtf8("lineEdit_30"))
        self.horizontalLayout_25.addWidget(self.lineEdit_30)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem25)
        self.gridLayout_6.addLayout(self.horizontalLayout_25, 0, 0, 1, 1)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_36 = QtGui.QLabel(self.tab_5)
        self.label_36.setMinimumSize(QtCore.QSize(90, 0))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_26.addWidget(self.label_36)
        self.lineEdit_31 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_31.setObjectName(_fromUtf8("lineEdit_31"))
        self.horizontalLayout_26.addWidget(self.lineEdit_31)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem26)
        self.gridLayout_6.addLayout(self.horizontalLayout_26, 1, 0, 1, 1)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_37 = QtGui.QLabel(self.tab_5)
        self.label_37.setMinimumSize(QtCore.QSize(90, 0))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_27.addWidget(self.label_37)
        self.spinBox = QtGui.QSpinBox(self.tab_5)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(255)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_27.addWidget(self.spinBox)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem27)
        self.gridLayout_6.addLayout(self.horizontalLayout_27, 2, 0, 1, 1)
        self.label_38 = QtGui.QLabel(self.tab_5)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_6.addWidget(self.label_38, 3, 0, 1, 1)
        self.textBrowser_5 = QtGui.QTextBrowser(self.tab_5)
        self.textBrowser_5.setObjectName(_fromUtf8("textBrowser_5"))
        self.gridLayout_6.addWidget(self.textBrowser_5, 4, 0, 1, 1)
        spacerItem28 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem28, 5, 0, 1, 1)
        self.instrumentBuilderTabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_39 = QtGui.QLabel(self.tab_6)
        self.label_39.setMinimumSize(QtCore.QSize(121, 0))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_28.addWidget(self.label_39)
        self.lineEdit_32 = QtGui.QLineEdit(self.tab_6)
        self.lineEdit_32.setObjectName(_fromUtf8("lineEdit_32"))
        self.horizontalLayout_28.addWidget(self.lineEdit_32)
        self.verticalLayout_2.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_40 = QtGui.QLabel(self.tab_6)
        self.label_40.setMinimumSize(QtCore.QSize(121, 0))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_29.addWidget(self.label_40)
        self.spinBox_2 = QtGui.QSpinBox(self.tab_6)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.horizontalLayout_29.addWidget(self.spinBox_2)
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem29)
        self.verticalLayout_2.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_41 = QtGui.QLabel(self.tab_6)
        self.label_41.setMinimumSize(QtCore.QSize(121, 28))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.horizontalLayout_30.addWidget(self.label_41)
        self.lineEdit_33 = QtGui.QLineEdit(self.tab_6)
        self.lineEdit_33.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_33.setObjectName(_fromUtf8("lineEdit_33"))
        self.horizontalLayout_30.addWidget(self.lineEdit_33)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem30)
        self.verticalLayout_2.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_42 = QtGui.QLabel(self.tab_6)
        self.label_42.setMinimumSize(QtCore.QSize(85, 0))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.horizontalLayout_31.addWidget(self.label_42)
        self.lineEdit_34 = QtGui.QLineEdit(self.tab_6)
        self.lineEdit_34.setObjectName(_fromUtf8("lineEdit_34"))
        self.horizontalLayout_31.addWidget(self.lineEdit_34)
        self.verticalLayout_2.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_43 = QtGui.QLabel(self.tab_6)
        self.label_43.setMinimumSize(QtCore.QSize(85, 28))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.horizontalLayout_32.addWidget(self.label_43)
        self.comboBox_4 = QtGui.QComboBox(self.tab_6)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.horizontalLayout_32.addWidget(self.comboBox_4)
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem31)
        self.verticalLayout_2.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.label_44 = QtGui.QLabel(self.tab_6)
        self.label_44.setMinimumSize(QtCore.QSize(163, 0))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.horizontalLayout_33.addWidget(self.label_44)
        self.lineEdit_35 = QtGui.QLineEdit(self.tab_6)
        self.lineEdit_35.setObjectName(_fromUtf8("lineEdit_35"))
        self.horizontalLayout_33.addWidget(self.lineEdit_35)
        self.verticalLayout_2.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label_45 = QtGui.QLabel(self.tab_6)
        self.label_45.setMinimumSize(QtCore.QSize(163, 29))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.horizontalLayout_34.addWidget(self.label_45)
        self.lineEdit_36 = QtGui.QLineEdit(self.tab_6)
        self.lineEdit_36.setObjectName(_fromUtf8("lineEdit_36"))
        self.horizontalLayout_34.addWidget(self.lineEdit_36)
        self.verticalLayout_2.addLayout(self.horizontalLayout_34)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.label_47 = QtGui.QLabel(self.groupBox_2)
        self.label_47.setMinimumSize(QtCore.QSize(52, 27))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.horizontalLayout_35.addWidget(self.label_47)
        self.lineEdit_37 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_37.setObjectName(_fromUtf8("lineEdit_37"))
        self.horizontalLayout_35.addWidget(self.lineEdit_37)
        self.gridLayout_7.addLayout(self.horizontalLayout_35, 0, 0, 1, 1)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.label_48 = QtGui.QLabel(self.groupBox_2)
        self.label_48.setMinimumSize(QtCore.QSize(52, 0))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.horizontalLayout_36.addWidget(self.label_48)
        self.lineEdit_38 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_38.setObjectName(_fromUtf8("lineEdit_38"))
        self.horizontalLayout_36.addWidget(self.lineEdit_38)
        self.gridLayout_7.addLayout(self.horizontalLayout_36, 1, 0, 1, 1)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_49 = QtGui.QLabel(self.groupBox_2)
        self.label_49.setMinimumSize(QtCore.QSize(52, 0))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.horizontalLayout_37.addWidget(self.label_49)
        self.lineEdit_39 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_39.setObjectName(_fromUtf8("lineEdit_39"))
        self.horizontalLayout_37.addWidget(self.lineEdit_39)
        self.gridLayout_7.addLayout(self.horizontalLayout_37, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.label_51 = QtGui.QLabel(self.groupBox_3)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.horizontalLayout_38.addWidget(self.label_51)
        self.comboBox_5 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.horizontalLayout_38.addWidget(self.comboBox_5)
        spacerItem32 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem32)
        self.gridLayout_8.addLayout(self.horizontalLayout_38, 0, 0, 1, 1)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.label_52 = QtGui.QLabel(self.groupBox_3)
        self.label_52.setMinimumSize(QtCore.QSize(52, 0))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.horizontalLayout_39.addWidget(self.label_52)
        self.lineEdit_40 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_40.setObjectName(_fromUtf8("lineEdit_40"))
        self.horizontalLayout_39.addWidget(self.lineEdit_40)
        spacerItem33 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem33)
        self.gridLayout_8.addLayout(self.horizontalLayout_39, 1, 0, 1, 1)
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.label_53 = QtGui.QLabel(self.groupBox_3)
        self.label_53.setMinimumSize(QtCore.QSize(52, 0))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.horizontalLayout_40.addWidget(self.label_53)
        self.lineEdit_41 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_41.setObjectName(_fromUtf8("lineEdit_41"))
        self.horizontalLayout_40.addWidget(self.lineEdit_41)
        self.gridLayout_8.addLayout(self.horizontalLayout_40, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.gridLayout_9.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_54 = QtGui.QLabel(self.tab_6)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.verticalLayout_3.addWidget(self.label_54)
        self.textBrowser_6 = QtGui.QTextBrowser(self.tab_6)
        self.textBrowser_6.setObjectName(_fromUtf8("textBrowser_6"))
        self.verticalLayout_3.addWidget(self.textBrowser_6)
        self.gridLayout_9.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.instrumentBuilderTabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.textBrowser_7 = QtGui.QTextBrowser(self.tab_7)
        self.textBrowser_7.setObjectName(_fromUtf8("textBrowser_7"))
        self.gridLayout_10.addWidget(self.textBrowser_7, 0, 0, 1, 1)
        self.instrumentBuilderTabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.gridLayout.addWidget(self.instrumentBuilderTabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.instrumentBuilderTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Instrument Builder", None))
        self.groupBox.setTitle(_translate("Dialog", "Toolbox", None))
        self.createInstrumentPushButton.setText(_translate("Dialog", "Create Instrument XML", None))
        self.setTabContentsPushButton.setText(_translate("Dialog", "Save Tab Contents", None))
        self.pushButton_10.setText(_translate("Dialog", "Add Core Module", None))
        self.enableInstrumentPushButton.setText(_translate("Dialog", "Create Instruments Loader", None))
        self.label_4.setText(_translate("Dialog", "Starinet Address", None))
        self.label.setText(_translate("Dialog", "Identifier", None))
        self.label_5.setText(_translate("Dialog", "Starinet Port", None))
        self.label_8.setText(_translate("Dialog", "Filename", None))
        self.label_9.setText(_translate("Dialog", ".xml", None))
        self.label_3.setText(_translate("Dialog", "Staribus Address", None))
        self.label_2.setText(_translate("Dialog", "Description", None))
        self.label_6.setText(_translate("Dialog", "Number of Channels", None))
        self.label_7.setText(_translate("Dialog", "Help", None))
        self.instrumentBuilderTabWidget.setTabText(self.instrumentBuilderTabWidget.indexOf(self.tab), _translate("Dialog", "Instrument", None))
        self.label_10.setText(_translate("Dialog", "X axis label", None))
        self.label_11.setText(_translate("Dialog", "Y axis label", None))
        self.label_12.setText(_translate("Dialog", "Y axis scale", None))
        self.label_13.setText(_translate("Dialog", "Y axis range", None))
        self.label_33.setText(_translate("Dialog", "Min", None))
        self.label_34.setText(_translate("Dialog", "Max", None))
        self.label_14.setText(_translate("Dialog", "Help", None))
        self.instrumentBuilderTabWidget.setTabText(self.instrumentBuilderTabWidget.indexOf(self.tab_2), _translate("Dialog", "ChartMetadata", None))
        self.label_24.setText(_translate("Dialog", "Channel", None))
        self.label_25.setText(_translate("Dialog", "Label", None))
        self.label_26.setText(_translate("Dialog", "Hex Colour", None))
        self.label_15.setText(_translate("Dialog", "Channel 0", None))
        self.pushButton.setText(_translate("Dialog", "Colour Chooser", None))
        self.label_16.setText(_translate("Dialog", "Channel 1", None))
        self.pushButton_2.setText(_translate("Dialog", "Colour Chooser", None))
        self.label_17.setText(_translate("Dialog", "Channel 2", None))
        self.pushButton_3.setText(_translate("Dialog", "Colour Chooser", None))
        self.label_18.setText(_translate("Dialog", "Channel 3", None))
        self.pushButton_4.setText(_translate("Dialog", "Colour Chooser", None))
        self.label_19.setText(_translate("Dialog", "Channel 4", None))
        self.pushButton_5.setText(_translate("Dialog", "Colour Chooser", None))
        self.label_20.setText(_translate("Dialog", "Channel 5", None))
        self.pushButton_6.setText(_translate("Dialog", "Colour Chooser", None))
        self.label_21.setText(_translate("Dialog", "Channel 6", None))
        self.pushButton_7.setText(_translate("Dialog", "Colour Chooser", None))
        self.label_22.setText(_translate("Dialog", "Channel 7", None))
        self.pushButton_8.setText(_translate("Dialog", "Colour Chooser", None))
        self.label_23.setText(_translate("Dialog", "Channel 8", None))
        self.pushButton_9.setText(_translate("Dialog", "Colour Chooser", None))
        self.label_27.setText(_translate("Dialog", "Help", None))
        self.instrumentBuilderTabWidget.setTabText(self.instrumentBuilderTabWidget.indexOf(self.tab_3), _translate("Dialog", "ChannelMetadata", None))
        self.label_29.setText(_translate("Dialog", "False", None))
        self.checkBox_2.setText(_translate("Dialog", "Default", None))
        self.label_31.setText(_translate("Dialog", "String", None))
        self.label_32.setText(_translate("Dialog", "Help", None))
        self.label_28.setText(_translate("Dialog", "True", None))
        self.checkBox.setText(_translate("Dialog", "Default", None))
        self.label_30.setText(_translate("Dialog", "String", None))
        self.instrumentBuilderTabWidget.setTabText(self.instrumentBuilderTabWidget.indexOf(self.tab_4), _translate("Dialog", "BooleanMetadata", None))
        self.label_35.setText(_translate("Dialog", "Identifier", None))
        self.label_36.setText(_translate("Dialog", "Description", None))
        self.label_37.setText(_translate("Dialog", "Code Base", None))
        self.label_38.setText(_translate("Dialog", "Help", None))
        self.instrumentBuilderTabWidget.setTabText(self.instrumentBuilderTabWidget.indexOf(self.tab_5), _translate("Dialog", "PluginMetadata", None))
        self.label_39.setText(_translate("Dialog", "Identifier", None))
        self.label_40.setText(_translate("Dialog", "Command Code", None))
        self.label_41.setText(_translate("Dialog", "Command Variant", None))
        self.label_42.setText(_translate("Dialog", "Description", None))
        self.label_43.setText(_translate("Dialog", "Send to Port", None))
        self.label_44.setText(_translate("Dialog", "Blocked Data Command", None))
        self.label_45.setText(_translate("Dialog", "Stepped Data Command", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Parameter", None))
        self.label_47.setText(_translate("Dialog", "Choices", None))
        self.label_48.setText(_translate("Dialog", "Regex", None))
        self.label_49.setText(_translate("Dialog", "Tooltip", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Response", None))
        self.label_51.setText(_translate("Dialog", "Data Type Name", None))
        self.label_52.setText(_translate("Dialog", "Units", None))
        self.label_53.setText(_translate("Dialog", "Regex", None))
        self.label_54.setText(_translate("Dialog", "Help", None))
        self.instrumentBuilderTabWidget.setTabText(self.instrumentBuilderTabWidget.indexOf(self.tab_6), _translate("Dialog", "CommandMetadata", None))
        self.instrumentBuilderTabWidget.setTabText(self.instrumentBuilderTabWidget.indexOf(self.tab_7), _translate("Dialog", "Help", None))

