from filters.NonLinearStaticRemover import NonlinearStaticRemover
from filters.PeakExtractor import PeakExtractor
from filters.RunningAverage import RunningAverage
from filters.WeightedRunningAverage import WeightedRunningAverage
