# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuration.ui'
#
# Created: Wed May 11 14:29:48 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui


class Ui_ConfigurationDialog(object):
    def setupUi(self, ConfigurationDialog):
        ConfigurationDialog.setObjectName("ConfigurationDialog")
        ConfigurationDialog.resize(699, 632)
        self.gridLayout = QtGui.QGridLayout(ConfigurationDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(ConfigurationDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_30.addWidget(self.label_4)
        self.relayCheckBox = QtGui.QCheckBox(self.groupBox_3)
        self.relayCheckBox.setObjectName("relayCheckBox")
        self.horizontalLayout_30.addWidget(self.relayCheckBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem)
        self.gridLayout_5.addLayout(self.horizontalLayout_30, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.ipAddressLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.ipAddressLineEdit.setObjectName("ipAddressLineEdit")
        self.horizontalLayout_7.addWidget(self.ipAddressLineEdit)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.portLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.portLineEdit.setObjectName("portLineEdit")
        self.horizontalLayout_7.addWidget(self.portLineEdit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 3, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_33 = QtGui.QLabel(self.groupBox_5)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_33.addWidget(self.label_33)
        self.legendLocationComboBox = QtGui.QComboBox(self.groupBox_5)
        self.legendLocationComboBox.setObjectName("legendLocationComboBox")
        self.horizontalLayout_33.addWidget(self.legendLocationComboBox)
        self.label_34 = QtGui.QLabel(self.groupBox_5)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_33.addWidget(self.label_34)
        self.LegendColSpinBox = QtGui.QSpinBox(self.groupBox_5)
        self.LegendColSpinBox.setMinimum(1)
        self.LegendColSpinBox.setMaximum(6)
        self.LegendColSpinBox.setSingleStep(1)
        self.LegendColSpinBox.setObjectName("LegendColSpinBox")
        self.horizontalLayout_33.addWidget(self.LegendColSpinBox)
        self.label_35 = QtGui.QLabel(self.groupBox_5)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_33.addWidget(self.label_35)
        self.LegendFontComboBox = QtGui.QComboBox(self.groupBox_5)
        self.LegendFontComboBox.setObjectName("LegendFontComboBox")
        self.horizontalLayout_33.addWidget(self.LegendFontComboBox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem3)
        self.gridLayout_8.addLayout(self.horizontalLayout_33, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_30 = QtGui.QLabel(self.groupBox)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_22.addWidget(self.label_30)
        self.loglevelComboBox = QtGui.QComboBox(self.groupBox)
        self.loglevelComboBox.setObjectName("loglevelComboBox")
        self.horizontalLayout_22.addWidget(self.loglevelComboBox)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem4)
        self.UpgradecheckBox = QtGui.QCheckBox(self.groupBox)
        self.UpgradecheckBox.setObjectName("UpgradecheckBox")
        self.horizontalLayout_22.addWidget(self.UpgradecheckBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_22, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.savepathLineEdit = QtGui.QLineEdit(self.groupBox)
        self.savepathLineEdit.setObjectName("savepathLineEdit")
        self.horizontalLayout_2.addWidget(self.savepathLineEdit)
        self.chooserButton = QtGui.QPushButton(self.groupBox)
        self.chooserButton.setObjectName("chooserButton")
        self.horizontalLayout_2.addWidget(self.chooserButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.OyNameLineEdit = QtGui.QLineEdit(self.tab_2)
        self.OyNameLineEdit.setObjectName("OyNameLineEdit")
        self.horizontalLayout_8.addWidget(self.OyNameLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.OyDescriptionLineEdit = QtGui.QLineEdit(self.tab_2)
        self.OyDescriptionLineEdit.setObjectName("OyDescriptionLineEdit")
        self.horizontalLayout_9.addWidget(self.OyDescriptionLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.OyEmailLineEdit = QtGui.QLineEdit(self.tab_2)
        self.OyEmailLineEdit.setObjectName("OyEmailLineEdit")
        self.horizontalLayout_10.addWidget(self.OyEmailLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_10, 2, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.OyTelephoneLineEdit = QtGui.QLineEdit(self.tab_2)
        self.OyTelephoneLineEdit.setObjectName("OyTelephoneLineEdit")
        self.horizontalLayout_11.addWidget(self.OyTelephoneLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_11, 3, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.OyUrlLineEdit = QtGui.QLineEdit(self.tab_2)
        self.OyUrlLineEdit.setObjectName("OyUrlLineEdit")
        self.horizontalLayout_12.addWidget(self.OyUrlLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_12, 4, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.OyCountryLineEdit = QtGui.QLineEdit(self.tab_2)
        self.OyCountryLineEdit.setObjectName("OyCountryLineEdit")
        self.horizontalLayout_13.addWidget(self.OyCountryLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_13, 5, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.OyTimezoneLineEdit = QtGui.QLineEdit(self.tab_2)
        self.OyTimezoneLineEdit.setObjectName("OyTimezoneLineEdit")
        self.horizontalLayout_14.addWidget(self.OyTimezoneLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_14, 6, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_20 = QtGui.QLabel(self.tab_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_15.addWidget(self.label_20)
        self.OyLongitudeLineEdit = QtGui.QLineEdit(self.tab_2)
        self.OyLongitudeLineEdit.setObjectName("OyLongitudeLineEdit")
        self.horizontalLayout_15.addWidget(self.OyLongitudeLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_15, 7, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_21 = QtGui.QLabel(self.tab_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_16.addWidget(self.label_21)
        self.OyLatitudeLineEdit = QtGui.QLineEdit(self.tab_2)
        self.OyLatitudeLineEdit.setObjectName("OyLatitudeLineEdit")
        self.horizontalLayout_16.addWidget(self.OyLatitudeLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_16, 8, 0, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_22 = QtGui.QLabel(self.tab_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_17.addWidget(self.label_22)
        self.OyHaslLineEdit = QtGui.QLineEdit(self.tab_2)
        self.OyHaslLineEdit.setObjectName("OyHaslLineEdit")
        self.horizontalLayout_17.addWidget(self.OyHaslLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_17, 9, 0, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_18.addWidget(self.label_16)
        self.OyDatumLineEdit = QtGui.QLineEdit(self.tab_2)
        self.OyDatumLineEdit.setObjectName("OyDatumLineEdit")
        self.horizontalLayout_18.addWidget(self.OyDatumLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_18, 10, 0, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        self.OyModelLineEdit = QtGui.QLineEdit(self.tab_2)
        self.OyModelLineEdit.setObjectName("OyModelLineEdit")
        self.horizontalLayout_19.addWidget(self.OyModelLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_19, 11, 0, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_20.addWidget(self.label_17)
        self.OyMagLongitudeLineEdit = QtGui.QLineEdit(self.tab_2)
        self.OyMagLongitudeLineEdit.setObjectName("OyMagLongitudeLineEdit")
        self.horizontalLayout_20.addWidget(self.OyMagLongitudeLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_20, 12, 0, 1, 1)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_21.addWidget(self.label_18)
        self.OyMagLatitudeLineEdit = QtGui.QLineEdit(self.tab_2)
        self.OyMagLatitudeLineEdit.setObjectName("OyMagLatitudeLineEdit")
        self.horizontalLayout_21.addWidget(self.OyMagLatitudeLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_21, 13, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_23.addWidget(self.label_23)
        self.ObNameLineEdit = QtGui.QLineEdit(self.tab_3)
        self.ObNameLineEdit.setObjectName("ObNameLineEdit")
        self.horizontalLayout_23.addWidget(self.ObNameLineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_23, 0, 0, 1, 1)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_24 = QtGui.QLabel(self.tab_3)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_24.addWidget(self.label_24)
        self.ObDescriptionLineEdit = QtGui.QLineEdit(self.tab_3)
        self.ObDescriptionLineEdit.setObjectName("ObDescriptionLineEdit")
        self.horizontalLayout_24.addWidget(self.ObDescriptionLineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_24, 1, 0, 1, 1)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_26 = QtGui.QLabel(self.tab_3)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_26.addWidget(self.label_26)
        self.ObTelephoneLineEdit = QtGui.QLineEdit(self.tab_3)
        self.ObTelephoneLineEdit.setObjectName("ObTelephoneLineEdit")
        self.horizontalLayout_26.addWidget(self.ObTelephoneLineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_26, 3, 0, 1, 1)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_25 = QtGui.QLabel(self.tab_3)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_25.addWidget(self.label_25)
        self.ObEmailLineEdit = QtGui.QLineEdit(self.tab_3)
        self.ObEmailLineEdit.setObjectName("ObEmailLineEdit")
        self.horizontalLayout_25.addWidget(self.ObEmailLineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_25, 2, 0, 1, 1)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_28 = QtGui.QLabel(self.tab_3)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_28.addWidget(self.label_28)
        self.ObCountryLineEdit = QtGui.QLineEdit(self.tab_3)
        self.ObCountryLineEdit.setObjectName("ObCountryLineEdit")
        self.horizontalLayout_28.addWidget(self.ObCountryLineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_28, 5, 0, 1, 1)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_27 = QtGui.QLabel(self.tab_3)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_27.addWidget(self.label_27)
        self.ObUrlLineEdit = QtGui.QLineEdit(self.tab_3)
        self.ObUrlLineEdit.setObjectName("ObUrlLineEdit")
        self.horizontalLayout_27.addWidget(self.ObUrlLineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_27, 4, 0, 1, 1)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_29 = QtGui.QLabel(self.tab_3)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_29.addWidget(self.label_29)
        self.ObNotesLineEdit = QtGui.QLineEdit(self.tab_3)
        self.ObNotesLineEdit.setObjectName("ObNotesLineEdit")
        self.horizontalLayout_29.addWidget(self.ObNotesLineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_29, 6, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem5, 7, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.saveButton = QtGui.QPushButton(ConfigurationDialog)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.cancelButton = QtGui.QPushButton(ConfigurationDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(ConfigurationDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ConfigurationDialog)

    def retranslateUi(self, ConfigurationDialog):
        ConfigurationDialog.setWindowTitle(QtGui.QApplication.translate("ConfigurationDialog", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ConfigurationDialog", "Staribus/ Starinet Relay", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ConfigurationDialog", "Relay", None, QtGui.QApplication.UnicodeUTF8))
        self.relayCheckBox.setText(QtGui.QApplication.translate("ConfigurationDialog", "Active", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ConfigurationDialog", "IP Address", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ConfigurationDialog", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("ConfigurationDialog", "Chart Legend Attributes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("ConfigurationDialog", "Legend Location", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("ConfigurationDialog", "Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("ConfigurationDialog", "Font Size", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ConfigurationDialog", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("ConfigurationDialog", "Log Level", None, QtGui.QApplication.UnicodeUTF8))
        self.UpgradecheckBox.setText(QtGui.QApplication.translate("ConfigurationDialog", "Check for upgrade, requires internet access.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ConfigurationDialog", "Data Save Path", None, QtGui.QApplication.UnicodeUTF8))
        self.chooserButton.setText(QtGui.QApplication.translate("ConfigurationDialog", "Chooser", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("ConfigurationDialog", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ConfigurationDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("ConfigurationDialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("ConfigurationDialog", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("ConfigurationDialog", "Telephone", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("ConfigurationDialog", "URL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("ConfigurationDialog", "Country", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("ConfigurationDialog", "Time Zone", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("ConfigurationDialog", "Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("ConfigurationDialog", "Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("ConfigurationDialog", "Height Above Sea Level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("ConfigurationDialog", "Geodetic Datum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("ConfigurationDialog", "Geomagnetic Model", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("ConfigurationDialog", "Geomagnetic Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("ConfigurationDialog", "Geomagnetic Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("ConfigurationDialog", "Observatory Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("ConfigurationDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("ConfigurationDialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("ConfigurationDialog", "Telephone", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("ConfigurationDialog", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("ConfigurationDialog", "Country", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("ConfigurationDialog", "URL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("ConfigurationDialog", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("ConfigurationDialog", "Observer Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("ConfigurationDialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("ConfigurationDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

