# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuration.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConfigurationDialog(object):
    def setupUi(self, ConfigurationDialog):
        ConfigurationDialog.setObjectName("ConfigurationDialog")
        ConfigurationDialog.resize(699, 632)
        self.gridLayout = QtWidgets.QGridLayout(ConfigurationDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(ConfigurationDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_30.addWidget(self.label_4)
        self.relayCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.relayCheckBox.setObjectName("relayCheckBox")
        self.horizontalLayout_30.addWidget(self.relayCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem)
        self.gridLayout_5.addLayout(self.horizontalLayout_30, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.ipAddressLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.ipAddressLineEdit.setObjectName("ipAddressLineEdit")
        self.horizontalLayout_7.addWidget(self.ipAddressLineEdit)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.portLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.portLineEdit.setObjectName("portLineEdit")
        self.horizontalLayout_7.addWidget(self.portLineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 3, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_33.addWidget(self.label_33)
        self.legendLocationComboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.legendLocationComboBox.setObjectName("legendLocationComboBox")
        self.horizontalLayout_33.addWidget(self.legendLocationComboBox)
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_33.addWidget(self.label_34)
        self.LegendColSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.LegendColSpinBox.setMinimum(1)
        self.LegendColSpinBox.setMaximum(6)
        self.LegendColSpinBox.setSingleStep(1)
        self.LegendColSpinBox.setObjectName("LegendColSpinBox")
        self.horizontalLayout_33.addWidget(self.LegendColSpinBox)
        self.label_35 = QtWidgets.QLabel(self.groupBox_5)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_33.addWidget(self.label_35)
        self.LegendFontComboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.LegendFontComboBox.setObjectName("LegendFontComboBox")
        self.horizontalLayout_33.addWidget(self.LegendFontComboBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem3)
        self.gridLayout_8.addLayout(self.horizontalLayout_33, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_22.addWidget(self.label_30)
        self.loglevelComboBox = QtWidgets.QComboBox(self.groupBox)
        self.loglevelComboBox.setObjectName("loglevelComboBox")
        self.horizontalLayout_22.addWidget(self.loglevelComboBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem4)
        self.UpgradecheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.UpgradecheckBox.setObjectName("UpgradecheckBox")
        self.horizontalLayout_22.addWidget(self.UpgradecheckBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_22, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.savepathLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.savepathLineEdit.setObjectName("savepathLineEdit")
        self.horizontalLayout_2.addWidget(self.savepathLineEdit)
        self.chooserButton = QtWidgets.QPushButton(self.groupBox)
        self.chooserButton.setObjectName("chooserButton")
        self.horizontalLayout_2.addWidget(self.chooserButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.OyNameLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.OyNameLineEdit.setObjectName("OyNameLineEdit")
        self.horizontalLayout_8.addWidget(self.OyNameLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.OyDescriptionLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.OyDescriptionLineEdit.setObjectName("OyDescriptionLineEdit")
        self.horizontalLayout_9.addWidget(self.OyDescriptionLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.OyEmailLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.OyEmailLineEdit.setObjectName("OyEmailLineEdit")
        self.horizontalLayout_10.addWidget(self.OyEmailLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_10, 2, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.OyTelephoneLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.OyTelephoneLineEdit.setObjectName("OyTelephoneLineEdit")
        self.horizontalLayout_11.addWidget(self.OyTelephoneLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_11, 3, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.OyUrlLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.OyUrlLineEdit.setObjectName("OyUrlLineEdit")
        self.horizontalLayout_12.addWidget(self.OyUrlLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_12, 4, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.OyCountryLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.OyCountryLineEdit.setObjectName("OyCountryLineEdit")
        self.horizontalLayout_13.addWidget(self.OyCountryLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_13, 5, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.OyTimezoneLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.OyTimezoneLineEdit.setObjectName("OyTimezoneLineEdit")
        self.horizontalLayout_14.addWidget(self.OyTimezoneLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_14, 6, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_15.addWidget(self.label_20)
        self.OyLongitudeLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.OyLongitudeLineEdit.setObjectName("OyLongitudeLineEdit")
        self.horizontalLayout_15.addWidget(self.OyLongitudeLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_15, 7, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_16.addWidget(self.label_21)
        self.OyLatitudeLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.OyLatitudeLineEdit.setObjectName("OyLatitudeLineEdit")
        self.horizontalLayout_16.addWidget(self.OyLatitudeLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_16, 8, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_17.addWidget(self.label_22)
        self.OyHaslLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.OyHaslLineEdit.setObjectName("OyHaslLineEdit")
        self.horizontalLayout_17.addWidget(self.OyHaslLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_17, 9, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_18.addWidget(self.label_16)
        self.OyDatumLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.OyDatumLineEdit.setObjectName("OyDatumLineEdit")
        self.horizontalLayout_18.addWidget(self.OyDatumLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_18, 10, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        self.OyModelLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.OyModelLineEdit.setObjectName("OyModelLineEdit")
        self.horizontalLayout_19.addWidget(self.OyModelLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_19, 11, 0, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_20.addWidget(self.label_17)
        self.OyMagLongitudeLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.OyMagLongitudeLineEdit.setObjectName("OyMagLongitudeLineEdit")
        self.horizontalLayout_20.addWidget(self.OyMagLongitudeLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_20, 12, 0, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_21.addWidget(self.label_18)
        self.OyMagLatitudeLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.OyMagLatitudeLineEdit.setObjectName("OyMagLatitudeLineEdit")
        self.horizontalLayout_21.addWidget(self.OyMagLatitudeLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_21, 13, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_23.addWidget(self.label_23)
        self.ObNameLineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.ObNameLineEdit.setObjectName("ObNameLineEdit")
        self.horizontalLayout_23.addWidget(self.ObNameLineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_23, 0, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_24.addWidget(self.label_24)
        self.ObDescriptionLineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.ObDescriptionLineEdit.setObjectName("ObDescriptionLineEdit")
        self.horizontalLayout_24.addWidget(self.ObDescriptionLineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_24, 1, 0, 1, 1)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_26.addWidget(self.label_26)
        self.ObTelephoneLineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.ObTelephoneLineEdit.setObjectName("ObTelephoneLineEdit")
        self.horizontalLayout_26.addWidget(self.ObTelephoneLineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_26, 3, 0, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_25.addWidget(self.label_25)
        self.ObEmailLineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.ObEmailLineEdit.setObjectName("ObEmailLineEdit")
        self.horizontalLayout_25.addWidget(self.ObEmailLineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_25, 2, 0, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_28 = QtWidgets.QLabel(self.tab_3)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_28.addWidget(self.label_28)
        self.ObCountryLineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.ObCountryLineEdit.setObjectName("ObCountryLineEdit")
        self.horizontalLayout_28.addWidget(self.ObCountryLineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_28, 5, 0, 1, 1)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_27.addWidget(self.label_27)
        self.ObUrlLineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.ObUrlLineEdit.setObjectName("ObUrlLineEdit")
        self.horizontalLayout_27.addWidget(self.ObUrlLineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_27, 4, 0, 1, 1)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_29 = QtWidgets.QLabel(self.tab_3)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_29.addWidget(self.label_29)
        self.ObNotesLineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.ObNotesLineEdit.setObjectName("ObNotesLineEdit")
        self.horizontalLayout_29.addWidget(self.ObNotesLineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_29, 6, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem5, 7, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.saveButton = QtWidgets.QPushButton(ConfigurationDialog)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(ConfigurationDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(ConfigurationDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ConfigurationDialog)

    def retranslateUi(self, ConfigurationDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfigurationDialog.setWindowTitle(_translate("ConfigurationDialog", "Configuration"))
        self.groupBox_3.setTitle(_translate("ConfigurationDialog", "Staribus/ Starinet Relay"))
        self.label_4.setText(_translate("ConfigurationDialog", "Relay"))
        self.relayCheckBox.setText(_translate("ConfigurationDialog", "Active"))
        self.label_7.setText(_translate("ConfigurationDialog", "IP Address"))
        self.label_8.setText(_translate("ConfigurationDialog", "Port"))
        self.groupBox_5.setTitle(_translate("ConfigurationDialog", "Chart Legend Attributes"))
        self.label_33.setText(_translate("ConfigurationDialog", "Legend Location"))
        self.label_34.setText(_translate("ConfigurationDialog", "Columns"))
        self.label_35.setText(_translate("ConfigurationDialog", "Font Size"))
        self.groupBox.setTitle(_translate("ConfigurationDialog", "General"))
        self.label_30.setText(_translate("ConfigurationDialog", "Log Level"))
        self.UpgradecheckBox.setText(_translate("ConfigurationDialog", "Check for upgrade, requires internet access."))
        self.label.setText(_translate("ConfigurationDialog", "Data Save Path"))
        self.chooserButton.setText(_translate("ConfigurationDialog", "Chooser"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ConfigurationDialog", "General"))
        self.label_9.setText(_translate("ConfigurationDialog", "Name"))
        self.label_10.setText(_translate("ConfigurationDialog", "Description"))
        self.label_11.setText(_translate("ConfigurationDialog", "Email"))
        self.label_12.setText(_translate("ConfigurationDialog", "Telephone"))
        self.label_13.setText(_translate("ConfigurationDialog", "URL"))
        self.label_14.setText(_translate("ConfigurationDialog", "Country"))
        self.label_15.setText(_translate("ConfigurationDialog", "Time Zone"))
        self.label_20.setText(_translate("ConfigurationDialog", "Longitude"))
        self.label_21.setText(_translate("ConfigurationDialog", "Latitude"))
        self.label_22.setText(_translate("ConfigurationDialog", "Height Above Sea Level"))
        self.label_16.setText(_translate("ConfigurationDialog", "Geodetic Datum"))
        self.label_19.setText(_translate("ConfigurationDialog", "Geomagnetic Model"))
        self.label_17.setText(_translate("ConfigurationDialog", "Geomagnetic Longitude"))
        self.label_18.setText(_translate("ConfigurationDialog", "Geomagnetic Latitude"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ConfigurationDialog", "Observatory Metadata"))
        self.label_23.setText(_translate("ConfigurationDialog", "Name"))
        self.label_24.setText(_translate("ConfigurationDialog", "Description"))
        self.label_26.setText(_translate("ConfigurationDialog", "Telephone"))
        self.label_25.setText(_translate("ConfigurationDialog", "Email"))
        self.label_28.setText(_translate("ConfigurationDialog", "Country"))
        self.label_27.setText(_translate("ConfigurationDialog", "URL"))
        self.label_29.setText(_translate("ConfigurationDialog", "Notes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ConfigurationDialog", "Observer Metadata"))
        self.saveButton.setText(_translate("ConfigurationDialog", "Save"))
        self.cancelButton.setText(_translate("ConfigurationDialog", "Cancel"))

