# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instrumentAttributes.ui'
#
# Created: Wed Sep  9 09:31:00 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_InstrumentAttributesDialog(object):
    def setupUi(self, InstrumentAttributesDialog):
        InstrumentAttributesDialog.setObjectName(_fromUtf8("InstrumentAttributesDialog"))
        InstrumentAttributesDialog.resize(554, 603)
        InstrumentAttributesDialog.setMinimumSize(QtCore.QSize(554, 603))
        InstrumentAttributesDialog.setMaximumSize(QtCore.QSize(554, 603))
        self.buttonBox = QtGui.QDialogButtonBox(InstrumentAttributesDialog)
        self.buttonBox.setGeometry(QtCore.QRect(190, 560, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.groupBox = QtGui.QGroupBox(InstrumentAttributesDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 531, 541))
        self.groupBox.setStyleSheet(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(90, 140, 66, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(250, 140, 66, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 20, 266, 101))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtGui.QComboBox(self.widget)
        self.comboBox.setMaxCount(253)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.StarinetAddressLineEdit = QtGui.QLineEdit(self.widget)
        self.StarinetAddressLineEdit.setMaxLength(15)
        self.StarinetAddressLineEdit.setObjectName(_fromUtf8("StarinetAddressLineEdit"))
        self.horizontalLayout_2.addWidget(self.StarinetAddressLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.StarinetPortLineEdit = QtGui.QLineEdit(self.widget)
        self.StarinetPortLineEdit.setMaxLength(5)
        self.StarinetPortLineEdit.setObjectName(_fromUtf8("StarinetPortLineEdit"))
        self.horizontalLayout_3.addWidget(self.StarinetPortLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.widget1 = QtGui.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(10, 160, 511, 321))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.widget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.Chan0LabelEdit = QtGui.QLineEdit(self.widget1)
        self.Chan0LabelEdit.setMaxLength(15)
        self.Chan0LabelEdit.setObjectName(_fromUtf8("Chan0LabelEdit"))
        self.horizontalLayout_4.addWidget(self.Chan0LabelEdit)
        self.Chan0ColourLineEdit = QtGui.QLineEdit(self.widget1)
        self.Chan0ColourLineEdit.setMaxLength(7)
        self.Chan0ColourLineEdit.setObjectName(_fromUtf8("Chan0ColourLineEdit"))
        self.horizontalLayout_4.addWidget(self.Chan0ColourLineEdit)
        self.PickerButton0 = QtGui.QPushButton(self.widget1)
        self.PickerButton0.setObjectName(_fromUtf8("PickerButton0"))
        self.horizontalLayout_4.addWidget(self.PickerButton0)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.widget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.Chan1LabelEdit = QtGui.QLineEdit(self.widget1)
        self.Chan1LabelEdit.setMaxLength(15)
        self.Chan1LabelEdit.setObjectName(_fromUtf8("Chan1LabelEdit"))
        self.horizontalLayout_5.addWidget(self.Chan1LabelEdit)
        self.Chan1ColourLineEdit = QtGui.QLineEdit(self.widget1)
        self.Chan1ColourLineEdit.setMaxLength(7)
        self.Chan1ColourLineEdit.setObjectName(_fromUtf8("Chan1ColourLineEdit"))
        self.horizontalLayout_5.addWidget(self.Chan1ColourLineEdit)
        self.PickerButton1 = QtGui.QPushButton(self.widget1)
        self.PickerButton1.setObjectName(_fromUtf8("PickerButton1"))
        self.horizontalLayout_5.addWidget(self.PickerButton1)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.widget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.Chan2LabelEdit = QtGui.QLineEdit(self.widget1)
        self.Chan2LabelEdit.setMaxLength(15)
        self.Chan2LabelEdit.setObjectName(_fromUtf8("Chan2LabelEdit"))
        self.horizontalLayout_6.addWidget(self.Chan2LabelEdit)
        self.Chan2ColourLineEdit = QtGui.QLineEdit(self.widget1)
        self.Chan2ColourLineEdit.setMaxLength(7)
        self.Chan2ColourLineEdit.setObjectName(_fromUtf8("Chan2ColourLineEdit"))
        self.horizontalLayout_6.addWidget(self.Chan2ColourLineEdit)
        self.PickerButton2 = QtGui.QPushButton(self.widget1)
        self.PickerButton2.setObjectName(_fromUtf8("PickerButton2"))
        self.horizontalLayout_6.addWidget(self.PickerButton2)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_7 = QtGui.QLabel(self.widget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.Chan3LabelEdit = QtGui.QLineEdit(self.widget1)
        self.Chan3LabelEdit.setMaxLength(15)
        self.Chan3LabelEdit.setObjectName(_fromUtf8("Chan3LabelEdit"))
        self.horizontalLayout_7.addWidget(self.Chan3LabelEdit)
        self.Chan3ColourLineEdit = QtGui.QLineEdit(self.widget1)
        self.Chan3ColourLineEdit.setMaxLength(7)
        self.Chan3ColourLineEdit.setObjectName(_fromUtf8("Chan3ColourLineEdit"))
        self.horizontalLayout_7.addWidget(self.Chan3ColourLineEdit)
        self.PickerButton3 = QtGui.QPushButton(self.widget1)
        self.PickerButton3.setObjectName(_fromUtf8("PickerButton3"))
        self.horizontalLayout_7.addWidget(self.PickerButton3)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_8 = QtGui.QLabel(self.widget1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_8.addWidget(self.label_8)
        self.Chan4LabelEdit = QtGui.QLineEdit(self.widget1)
        self.Chan4LabelEdit.setMaxLength(15)
        self.Chan4LabelEdit.setObjectName(_fromUtf8("Chan4LabelEdit"))
        self.horizontalLayout_8.addWidget(self.Chan4LabelEdit)
        self.Chan4ColourLineEdit = QtGui.QLineEdit(self.widget1)
        self.Chan4ColourLineEdit.setMaxLength(7)
        self.Chan4ColourLineEdit.setObjectName(_fromUtf8("Chan4ColourLineEdit"))
        self.horizontalLayout_8.addWidget(self.Chan4ColourLineEdit)
        self.PickerButton4 = QtGui.QPushButton(self.widget1)
        self.PickerButton4.setObjectName(_fromUtf8("PickerButton4"))
        self.horizontalLayout_8.addWidget(self.PickerButton4)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 4, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_9 = QtGui.QLabel(self.widget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_9.addWidget(self.label_9)
        self.Chan5LabelEdit = QtGui.QLineEdit(self.widget1)
        self.Chan5LabelEdit.setMaxLength(15)
        self.Chan5LabelEdit.setObjectName(_fromUtf8("Chan5LabelEdit"))
        self.horizontalLayout_9.addWidget(self.Chan5LabelEdit)
        self.Chan5ColourLineEdit = QtGui.QLineEdit(self.widget1)
        self.Chan5ColourLineEdit.setMaxLength(7)
        self.Chan5ColourLineEdit.setObjectName(_fromUtf8("Chan5ColourLineEdit"))
        self.horizontalLayout_9.addWidget(self.Chan5ColourLineEdit)
        self.PickerButton5 = QtGui.QPushButton(self.widget1)
        self.PickerButton5.setObjectName(_fromUtf8("PickerButton5"))
        self.horizontalLayout_9.addWidget(self.PickerButton5)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 5, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_10 = QtGui.QLabel(self.widget1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        self.Chan6LabelEdit = QtGui.QLineEdit(self.widget1)
        self.Chan6LabelEdit.setMaxLength(15)
        self.Chan6LabelEdit.setObjectName(_fromUtf8("Chan6LabelEdit"))
        self.horizontalLayout_10.addWidget(self.Chan6LabelEdit)
        self.Chan6ColourLineEdit = QtGui.QLineEdit(self.widget1)
        self.Chan6ColourLineEdit.setMaxLength(7)
        self.Chan6ColourLineEdit.setObjectName(_fromUtf8("Chan6ColourLineEdit"))
        self.horizontalLayout_10.addWidget(self.Chan6ColourLineEdit)
        self.PickerButton6 = QtGui.QPushButton(self.widget1)
        self.PickerButton6.setObjectName(_fromUtf8("PickerButton6"))
        self.horizontalLayout_10.addWidget(self.PickerButton6)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 6, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_11 = QtGui.QLabel(self.widget1)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_11.addWidget(self.label_11)
        self.Chan7LabelEdit = QtGui.QLineEdit(self.widget1)
        self.Chan7LabelEdit.setMaxLength(15)
        self.Chan7LabelEdit.setObjectName(_fromUtf8("Chan7LabelEdit"))
        self.horizontalLayout_11.addWidget(self.Chan7LabelEdit)
        self.Chan7ColourLineEdit = QtGui.QLineEdit(self.widget1)
        self.Chan7ColourLineEdit.setMaxLength(7)
        self.Chan7ColourLineEdit.setObjectName(_fromUtf8("Chan7ColourLineEdit"))
        self.horizontalLayout_11.addWidget(self.Chan7ColourLineEdit)
        self.PickerButton7 = QtGui.QPushButton(self.widget1)
        self.PickerButton7.setObjectName(_fromUtf8("PickerButton7"))
        self.horizontalLayout_11.addWidget(self.PickerButton7)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 7, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_12 = QtGui.QLabel(self.widget1)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_12.addWidget(self.label_12)
        self.Chan8LabelEdit = QtGui.QLineEdit(self.widget1)
        self.Chan8LabelEdit.setMaxLength(15)
        self.Chan8LabelEdit.setObjectName(_fromUtf8("Chan8LabelEdit"))
        self.horizontalLayout_12.addWidget(self.Chan8LabelEdit)
        self.Chan8ColourLineEdit = QtGui.QLineEdit(self.widget1)
        self.Chan8ColourLineEdit.setMaxLength(7)
        self.Chan8ColourLineEdit.setObjectName(_fromUtf8("Chan8ColourLineEdit"))
        self.horizontalLayout_12.addWidget(self.Chan8ColourLineEdit)
        self.PickerButton8 = QtGui.QPushButton(self.widget1)
        self.PickerButton8.setObjectName(_fromUtf8("PickerButton8"))
        self.horizontalLayout_12.addWidget(self.PickerButton8)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 8, 0, 1, 1)

        self.retranslateUi(InstrumentAttributesDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), InstrumentAttributesDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), InstrumentAttributesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(InstrumentAttributesDialog)

    def retranslateUi(self, InstrumentAttributesDialog):
        InstrumentAttributesDialog.setWindowTitle(_translate("InstrumentAttributesDialog", "Instrument Attributes", None))
        self.groupBox.setTitle(_translate("InstrumentAttributesDialog", "Instrument Attributes", None))
        self.label_13.setText(_translate("InstrumentAttributesDialog", "Label", None))
        self.label_14.setText(_translate("InstrumentAttributesDialog", "Colour", None))
        self.label.setText(_translate("InstrumentAttributesDialog", "Staribus Address", None))
        self.label_2.setText(_translate("InstrumentAttributesDialog", "Starinet IP Address", None))
        self.label_3.setText(_translate("InstrumentAttributesDialog", "Starinet Port", None))
        self.label_4.setText(_translate("InstrumentAttributesDialog", "Channel 0", None))
        self.PickerButton0.setText(_translate("InstrumentAttributesDialog", "Colour Picker", None))
        self.label_5.setText(_translate("InstrumentAttributesDialog", "Channel 1", None))
        self.PickerButton1.setText(_translate("InstrumentAttributesDialog", "Colour Picker", None))
        self.label_6.setText(_translate("InstrumentAttributesDialog", "Channel 2", None))
        self.PickerButton2.setText(_translate("InstrumentAttributesDialog", "Colour Picker", None))
        self.label_7.setText(_translate("InstrumentAttributesDialog", "Channel 3", None))
        self.PickerButton3.setText(_translate("InstrumentAttributesDialog", "Colour Picker", None))
        self.label_8.setText(_translate("InstrumentAttributesDialog", "Channel 4", None))
        self.PickerButton4.setText(_translate("InstrumentAttributesDialog", "Colour Picker", None))
        self.label_9.setText(_translate("InstrumentAttributesDialog", "Channel 5", None))
        self.PickerButton5.setText(_translate("InstrumentAttributesDialog", "Colour Picker", None))
        self.label_10.setText(_translate("InstrumentAttributesDialog", "Channel 6", None))
        self.PickerButton6.setText(_translate("InstrumentAttributesDialog", "Colour Picker", None))
        self.label_11.setText(_translate("InstrumentAttributesDialog", "Channel 7", None))
        self.PickerButton7.setText(_translate("InstrumentAttributesDialog", "Colour Picker", None))
        self.label_12.setText(_translate("InstrumentAttributesDialog", "Channel 8", None))
        self.PickerButton8.setText(_translate("InstrumentAttributesDialog", "Colour Picker", None))

